// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: javaDemo/v1/javaDemo.proto

// Protobuf Java Version: 3.25.1
package javaDemo/v1;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:javaDemo.v1.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   * @return The request.
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   * @return The bytes for request.
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
