// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: javaDemo/v1/javaDemo.proto

// Protobuf Java Version: 3.25.1
package javaDemo/v1;

public final class javaDemoProtoV1 {
  private javaDemoProtoV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_javaDemo_v1_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_javaDemo_v1_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_javaDemo_v1_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_javaDemo_v1_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032javaDemo/v1/javaDemo.proto\022\013javaDemo.v" +
      "1\032\034google/api/annotations.proto\"\037\n\014Hello" +
      "Request\022\017\n\007request\030\001 \001(\t\"!\n\rHelloRespons" +
      "e\022\020\n\010response\030\001 \001(\t2\311\002\n\017javaDemoService\022" +
      "S\n\nHelloWorld\022\031.javaDemo.v1.HelloRequest" +
      "\032\032.javaDemo.v1.HelloResponse\"\016\202\323\344\223\002\010\"\006/h" +
      "ello\022h\n\026HelloWorldClientStream\022\031.javaDem" +
      "o.v1.HelloRequest\032\032.javaDemo.v1.HelloRes" +
      "ponse\"\025\202\323\344\223\002\017\"\r/hello/stream(\001\022w\n\037HelloW" +
      "orldClientAndServerStream\022\031.javaDemo.v1." +
      "HelloRequest\032\032.javaDemo.v1.HelloResponse" +
      "\"\031\202\323\344\223\002\023\"\021/hello/bothStream(\0010\001BV\n\013javaD" +
      "emo/v1B\017javaDemoProtoV1P\001Z1github.com/ZL" +
      "SMDB/lsmdb_server/api/javaDemo/v1;v1\210\001\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_javaDemo_v1_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_javaDemo_v1_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_javaDemo_v1_HelloRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_javaDemo_v1_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_javaDemo_v1_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_javaDemo_v1_HelloResponse_descriptor,
        new java.lang.String[] { "Response", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
