// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v5.26.0--rc1
// source: api/lsmdb/v1/lsmdb.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLsmdbCloseDB = "/lsmdb.v1.Lsmdb/CloseDB"
const OperationLsmdbGet = "/lsmdb.v1.Lsmdb/Get"
const OperationLsmdbOpenDB = "/lsmdb.v1.Lsmdb/OpenDB"
const OperationLsmdbPut = "/lsmdb.v1.Lsmdb/Put"
const OperationLsmdbPutStr = "/lsmdb.v1.Lsmdb/PutStr"

type LsmdbHTTPServer interface {
	CloseDB(context.Context, *CloseDBRequest) (*CloseDBReply, error)
	// Get
	//rpc Get (GetRequest) returns (stream GetReply) {
	//option (google.api.http) = {
	//get: "/lsmdb/get/{key}"
	//};
	//}
	Get(context.Context, *GetRequest) (*GetReply, error)
	// OpenDB Sends a register
	OpenDB(context.Context, *OpenDBRequest) (*OpenDBReply, error)
	// Put
	//rpc Put (stream PutRequest) returns (PutReply) {
	//option (google.api.http) = {
	//post: "/lsmdb/put"
	//body: "*"
	//};
	//}
	Put(context.Context, *PutRequest) (*PutReply, error)
	PutStr(context.Context, *PutStrRequest) (*PutStrReply, error)
}

func RegisterLsmdbHTTPServer(s *http.Server, srv LsmdbHTTPServer) {
	r := s.Route("/")
	r.POST("/lsmdb/opendb", _Lsmdb_OpenDB0_HTTP_Handler(srv))
	r.POST("/lsmdb/put", _Lsmdb_Put0_HTTP_Handler(srv))
	r.POST("/lsmdb/putstr", _Lsmdb_PutStr0_HTTP_Handler(srv))
	r.GET("/lsmdb/get/{key:.*.*}", _Lsmdb_Get0_HTTP_Handler(srv))
	r.POST("/lsmdb/close", _Lsmdb_CloseDB0_HTTP_Handler(srv))
}

func _Lsmdb_OpenDB0_HTTP_Handler(srv LsmdbHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OpenDBRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLsmdbOpenDB)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OpenDB(ctx, req.(*OpenDBRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OpenDBReply)
		return ctx.Result(200, reply)
	}
}

func _Lsmdb_Put0_HTTP_Handler(srv LsmdbHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PutRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLsmdbPut)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Put(ctx, req.(*PutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PutReply)
		return ctx.Result(200, reply)
	}
}

func _Lsmdb_PutStr0_HTTP_Handler(srv LsmdbHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PutStrRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLsmdbPutStr)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PutStr(ctx, req.(*PutStrRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PutStrReply)
		return ctx.Result(200, reply)
	}
}

func _Lsmdb_Get0_HTTP_Handler(srv LsmdbHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLsmdbGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*GetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetReply)
		return ctx.Result(200, reply.Value)
	}
}

func _Lsmdb_CloseDB0_HTTP_Handler(srv LsmdbHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CloseDBRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLsmdbCloseDB)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CloseDB(ctx, req.(*CloseDBRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CloseDBReply)
		return ctx.Result(200, reply)
	}
}

type LsmdbHTTPClient interface {
	CloseDB(ctx context.Context, req *CloseDBRequest, opts ...http.CallOption) (rsp *CloseDBReply, err error)
	Get(ctx context.Context, req *GetRequest, opts ...http.CallOption) (rsp *GetReply, err error)
	OpenDB(ctx context.Context, req *OpenDBRequest, opts ...http.CallOption) (rsp *OpenDBReply, err error)
	Put(ctx context.Context, req *PutRequest, opts ...http.CallOption) (rsp *PutReply, err error)
	PutStr(ctx context.Context, req *PutStrRequest, opts ...http.CallOption) (rsp *PutStrReply, err error)
}

type LsmdbHTTPClientImpl struct {
	cc *http.Client
}

func NewLsmdbHTTPClient(client *http.Client) LsmdbHTTPClient {
	return &LsmdbHTTPClientImpl{client}
}

func (c *LsmdbHTTPClientImpl) CloseDB(ctx context.Context, in *CloseDBRequest, opts ...http.CallOption) (*CloseDBReply, error) {
	var out CloseDBReply
	pattern := "/lsmdb/close"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLsmdbCloseDB))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *LsmdbHTTPClientImpl) Get(ctx context.Context, in *GetRequest, opts ...http.CallOption) (*GetReply, error) {
	var out GetReply
	pattern := "/lsmdb/get/{key:.*.*}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLsmdbGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *LsmdbHTTPClientImpl) OpenDB(ctx context.Context, in *OpenDBRequest, opts ...http.CallOption) (*OpenDBReply, error) {
	var out OpenDBReply
	pattern := "/lsmdb/opendb"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLsmdbOpenDB))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *LsmdbHTTPClientImpl) Put(ctx context.Context, in *PutRequest, opts ...http.CallOption) (*PutReply, error) {
	var out PutReply
	pattern := "/lsmdb/put"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLsmdbPut))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *LsmdbHTTPClientImpl) PutStr(ctx context.Context, in *PutStrRequest, opts ...http.CallOption) (*PutStrReply, error) {
	var out PutStrReply
	pattern := "/lsmdb/putstr"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLsmdbPutStr))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
