// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.26.0
// source: api/lsmdb/v1/lsmdb.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKVsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *GetKVsRequest) Reset() {
	*x = GetKVsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKVsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKVsRequest) ProtoMessage() {}

func (x *GetKVsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKVsRequest.ProtoReflect.Descriptor instead.
func (*GetKVsRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{0}
}

func (x *GetKVsRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetKVsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *GetKVsReply) Reset() {
	*x = GetKVsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKVsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKVsReply) ProtoMessage() {}

func (x *GetKVsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKVsReply.ProtoReflect.Descriptor instead.
func (*GetKVsReply) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{1}
}

func (x *GetKVsReply) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type TransferKVRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionName  string   `protobuf:"bytes,1,opt,name=regionName,proto3" json:"regionName,omitempty"`
	Keys        []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	NodeAddress string   `protobuf:"bytes,3,opt,name=nodeAddress,proto3" json:"nodeAddress,omitempty"`
}

func (x *TransferKVRequest) Reset() {
	*x = TransferKVRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferKVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferKVRequest) ProtoMessage() {}

func (x *TransferKVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferKVRequest.ProtoReflect.Descriptor instead.
func (*TransferKVRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{2}
}

func (x *TransferKVRequest) GetRegionName() string {
	if x != nil {
		return x.RegionName
	}
	return ""
}

func (x *TransferKVRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *TransferKVRequest) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

type TransferKVReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *TransferKVReply) Reset() {
	*x = TransferKVReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferKVReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferKVReply) ProtoMessage() {}

func (x *TransferKVReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferKVReply.ProtoReflect.Descriptor instead.
func (*TransferKVReply) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{3}
}

func (x *TransferKVReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TransferRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionName  string   `protobuf:"bytes,1,opt,name=regionName,proto3" json:"regionName,omitempty"`
	Keys        []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	NodeAddress string   `protobuf:"bytes,3,opt,name=nodeAddress,proto3" json:"nodeAddress,omitempty"`
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{4}
}

func (x *TransferRequest) GetRegionName() string {
	if x != nil {
		return x.RegionName
	}
	return ""
}

func (x *TransferRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *TransferRequest) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

type TransferReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *TransferReply) Reset() {
	*x = TransferReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReply) ProtoMessage() {}

func (x *TransferReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReply.ProtoReflect.Descriptor instead.
func (*TransferReply) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{5}
}

func (x *TransferReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type OpenDBWebRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dbname string `protobuf:"bytes,1,opt,name=dbname,proto3" json:"dbname,omitempty"`
}

func (x *OpenDBWebRequest) Reset() {
	*x = OpenDBWebRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDBWebRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDBWebRequest) ProtoMessage() {}

func (x *OpenDBWebRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDBWebRequest.ProtoReflect.Descriptor instead.
func (*OpenDBWebRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{6}
}

func (x *OpenDBWebRequest) GetDbname() string {
	if x != nil {
		return x.Dbname
	}
	return ""
}

type OpenDBWebReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *OpenDBWebReply) Reset() {
	*x = OpenDBWebReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDBWebReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDBWebReply) ProtoMessage() {}

func (x *OpenDBWebReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDBWebReply.ProtoReflect.Descriptor instead.
func (*OpenDBWebReply) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{7}
}

func (x *OpenDBWebReply) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

// 命名必须使用下划线，否则出现传递不了参数的情况
type OpenDBRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbName string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
}

func (x *OpenDBRequest) Reset() {
	*x = OpenDBRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDBRequest) ProtoMessage() {}

func (x *OpenDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDBRequest.ProtoReflect.Descriptor instead.
func (*OpenDBRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{8}
}

func (x *OpenDBRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

// The response message containing the value about register success or not .
type OpenDBReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *OpenDBReply) Reset() {
	*x = OpenDBReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDBReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDBReply) ProtoMessage() {}

func (x *OpenDBReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDBReply.ProtoReflect.Descriptor instead.
func (*OpenDBReply) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{9}
}

func (x *OpenDBReply) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type PutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{10}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data bool `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PutReply) Reset() {
	*x = PutReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutReply) ProtoMessage() {}

func (x *PutReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutReply.ProtoReflect.Descriptor instead.
func (*PutReply) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{11}
}

func (x *PutReply) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type PutStrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PutStrRequest) Reset() {
	*x = PutStrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutStrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutStrRequest) ProtoMessage() {}

func (x *PutStrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutStrRequest.ProtoReflect.Descriptor instead.
func (*PutStrRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{12}
}

func (x *PutStrRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutStrRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PutStrReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data bool `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PutStrReply) Reset() {
	*x = PutStrReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutStrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutStrReply) ProtoMessage() {}

func (x *PutStrReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutStrReply.ProtoReflect.Descriptor instead.
func (*PutStrReply) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{13}
}

func (x *PutStrReply) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

// The request message containing mac addr and ip.
type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{14}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// The response message containing the value about register success or not .
type GetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{15}
}

func (x *GetReply) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CloseDBRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseDBRequest) Reset() {
	*x = CloseDBRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseDBRequest) ProtoMessage() {}

func (x *CloseDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseDBRequest.ProtoReflect.Descriptor instead.
func (*CloseDBRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{16}
}

type CloseDBReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseDBReply) Reset() {
	*x = CloseDBReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseDBReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseDBReply) ProtoMessage() {}

func (x *CloseDBReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseDBReply.ProtoReflect.Descriptor instead.
func (*CloseDBReply) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{17}
}

type CloseDBWebRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseDBWebRequest) Reset() {
	*x = CloseDBWebRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseDBWebRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseDBWebRequest) ProtoMessage() {}

func (x *CloseDBWebRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseDBWebRequest.ProtoReflect.Descriptor instead.
func (*CloseDBWebRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{18}
}

type CloseDBWebReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseDBWebReply) Reset() {
	*x = CloseDBWebReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseDBWebReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseDBWebReply) ProtoMessage() {}

func (x *CloseDBWebReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseDBWebReply.ProtoReflect.Descriptor instead.
func (*CloseDBWebReply) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{19}
}

var File_api_lsmdb_v1_lsmdb_proto protoreflect.FileDescriptor

var file_api_lsmdb_v1_lsmdb_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x6c,
	0x73, 0x6d, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6c, 0x73, 0x6d, 0x64,
	0x62, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4b, 0x56, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4b, 0x56,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x69,
	0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4b, 0x56, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x6f,
	0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x2b, 0x0a, 0x0f, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x4b, 0x56, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x67, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x20, 0x0a,
	0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x29, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2a, 0x0a, 0x10, 0x4f, 0x70,
	0x65, 0x6e, 0x44, 0x42, 0x57, 0x65, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x62, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x62, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0e, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x42,
	0x57, 0x65, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x28,
	0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x6e,
	0x44, 0x42, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x34, 0x0a,
	0x0a, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a, 0x08, 0x50, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x37, 0x0a, 0x0d, 0x50, 0x75, 0x74, 0x53, 0x74, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x0a, 0x0b,
	0x50, 0x75, 0x74, 0x53, 0x74, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x1e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x20, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x42, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x42, 0x57, 0x65,
	0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x44, 0x42, 0x57, 0x65, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xa6, 0x06, 0x0a, 0x05,
	0x4c, 0x73, 0x6d, 0x64, 0x62, 0x12, 0x4c, 0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x42, 0x12,
	0x17, 0x2e, 0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x44,
	0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x73, 0x6d, 0x64, 0x62,
	0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x42, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x22, 0x07, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x64, 0x62,
	0x3a, 0x01, 0x2a, 0x12, 0x5b, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x42, 0x57, 0x65, 0x62,
	0x12, 0x1a, 0x2e, 0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x6e,
	0x44, 0x42, 0x57, 0x65, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c,
	0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x42, 0x57, 0x65,
	0x62, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10,
	0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x64, 0x62, 0x2f, 0x7b, 0x64, 0x62, 0x6e, 0x61, 0x6d, 0x65, 0x7d,
	0x12, 0x40, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x14, 0x2e, 0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x0f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x09, 0x22, 0x04, 0x2f, 0x70, 0x75, 0x74, 0x3a,
	0x01, 0x2a, 0x12, 0x4c, 0x0a, 0x06, 0x50, 0x75, 0x74, 0x53, 0x74, 0x72, 0x12, 0x17, 0x2e, 0x6c,
	0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x53, 0x74, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x75, 0x74, 0x53, 0x74, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0c, 0x22, 0x07, 0x2f, 0x70, 0x75, 0x74, 0x73, 0x74, 0x72, 0x3a, 0x01, 0x2a,
	0x12, 0x46, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x14, 0x2e, 0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x67, 0x65, 0x74, 0x2f,
	0x7b, 0x6b, 0x65, 0x79, 0x3d, 0x2a, 0x2a, 0x7d, 0x12, 0x4b, 0x0a, 0x07, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x44, 0x42, 0x12, 0x18, 0x2e, 0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x42,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x08, 0x22, 0x06, 0x2f,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0a, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x42,
	0x57, 0x65, 0x62, 0x12, 0x1b, 0x2e, 0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x44, 0x42, 0x57, 0x65, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x44, 0x42, 0x57, 0x65, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0e, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x08, 0x12, 0x06, 0x2f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0a, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4b, 0x56, 0x12, 0x1b, 0x2e, 0x6c, 0x73, 0x6d, 0x64,
	0x62, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4b, 0x56, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4b, 0x56, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x22, 0x0b, 0x2f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x6b, 0x76, 0x12, 0x51, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x12, 0x19, 0x2e, 0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x22, 0x09,
	0x2f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x4b, 0x56, 0x73, 0x12, 0x17, 0x2e, 0x6c, 0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x4b, 0x56, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6c,
	0x73, 0x6d, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x56, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x0f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x09, 0x22, 0x07, 0x2f, 0x47, 0x65,
	0x74, 0x4b, 0x56, 0x73, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x5a, 0x4c, 0x53, 0x4d, 0x44, 0x42, 0x2f, 0x6c, 0x73, 0x6d, 0x64, 0x62, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x73, 0x6d, 0x64, 0x62,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_lsmdb_v1_lsmdb_proto_rawDescOnce sync.Once
	file_api_lsmdb_v1_lsmdb_proto_rawDescData = file_api_lsmdb_v1_lsmdb_proto_rawDesc
)

func file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP() []byte {
	file_api_lsmdb_v1_lsmdb_proto_rawDescOnce.Do(func() {
		file_api_lsmdb_v1_lsmdb_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_lsmdb_v1_lsmdb_proto_rawDescData)
	})
	return file_api_lsmdb_v1_lsmdb_proto_rawDescData
}

var file_api_lsmdb_v1_lsmdb_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_lsmdb_v1_lsmdb_proto_goTypes = []interface{}{
	(*GetKVsRequest)(nil),     // 0: lsmdb.v1.GetKVsRequest
	(*GetKVsReply)(nil),       // 1: lsmdb.v1.GetKVsReply
	(*TransferKVRequest)(nil), // 2: lsmdb.v1.TransferKVRequest
	(*TransferKVReply)(nil),   // 3: lsmdb.v1.TransferKVReply
	(*TransferRequest)(nil),   // 4: lsmdb.v1.TransferRequest
	(*TransferReply)(nil),     // 5: lsmdb.v1.TransferReply
	(*OpenDBWebRequest)(nil),  // 6: lsmdb.v1.OpenDBWebRequest
	(*OpenDBWebReply)(nil),    // 7: lsmdb.v1.OpenDBWebReply
	(*OpenDBRequest)(nil),     // 8: lsmdb.v1.OpenDBRequest
	(*OpenDBReply)(nil),       // 9: lsmdb.v1.OpenDBReply
	(*PutRequest)(nil),        // 10: lsmdb.v1.PutRequest
	(*PutReply)(nil),          // 11: lsmdb.v1.PutReply
	(*PutStrRequest)(nil),     // 12: lsmdb.v1.PutStrRequest
	(*PutStrReply)(nil),       // 13: lsmdb.v1.PutStrReply
	(*GetRequest)(nil),        // 14: lsmdb.v1.GetRequest
	(*GetReply)(nil),          // 15: lsmdb.v1.GetReply
	(*CloseDBRequest)(nil),    // 16: lsmdb.v1.CloseDBRequest
	(*CloseDBReply)(nil),      // 17: lsmdb.v1.CloseDBReply
	(*CloseDBWebRequest)(nil), // 18: lsmdb.v1.CloseDBWebRequest
	(*CloseDBWebReply)(nil),   // 19: lsmdb.v1.CloseDBWebReply
}
var file_api_lsmdb_v1_lsmdb_proto_depIdxs = []int32{
	8,  // 0: lsmdb.v1.Lsmdb.OpenDB:input_type -> lsmdb.v1.OpenDBRequest
	6,  // 1: lsmdb.v1.Lsmdb.OpenDBWeb:input_type -> lsmdb.v1.OpenDBWebRequest
	10, // 2: lsmdb.v1.Lsmdb.Put:input_type -> lsmdb.v1.PutRequest
	12, // 3: lsmdb.v1.Lsmdb.PutStr:input_type -> lsmdb.v1.PutStrRequest
	14, // 4: lsmdb.v1.Lsmdb.Get:input_type -> lsmdb.v1.GetRequest
	16, // 5: lsmdb.v1.Lsmdb.CloseDB:input_type -> lsmdb.v1.CloseDBRequest
	18, // 6: lsmdb.v1.Lsmdb.CloseDBWeb:input_type -> lsmdb.v1.CloseDBWebRequest
	2,  // 7: lsmdb.v1.Lsmdb.TransferKV:input_type -> lsmdb.v1.TransferKVRequest
	4,  // 8: lsmdb.v1.Lsmdb.Transfer:input_type -> lsmdb.v1.TransferRequest
	0,  // 9: lsmdb.v1.Lsmdb.GetKVs:input_type -> lsmdb.v1.GetKVsRequest
	9,  // 10: lsmdb.v1.Lsmdb.OpenDB:output_type -> lsmdb.v1.OpenDBReply
	7,  // 11: lsmdb.v1.Lsmdb.OpenDBWeb:output_type -> lsmdb.v1.OpenDBWebReply
	11, // 12: lsmdb.v1.Lsmdb.Put:output_type -> lsmdb.v1.PutReply
	13, // 13: lsmdb.v1.Lsmdb.PutStr:output_type -> lsmdb.v1.PutStrReply
	15, // 14: lsmdb.v1.Lsmdb.Get:output_type -> lsmdb.v1.GetReply
	17, // 15: lsmdb.v1.Lsmdb.CloseDB:output_type -> lsmdb.v1.CloseDBReply
	19, // 16: lsmdb.v1.Lsmdb.CloseDBWeb:output_type -> lsmdb.v1.CloseDBWebReply
	3,  // 17: lsmdb.v1.Lsmdb.TransferKV:output_type -> lsmdb.v1.TransferKVReply
	5,  // 18: lsmdb.v1.Lsmdb.Transfer:output_type -> lsmdb.v1.TransferReply
	1,  // 19: lsmdb.v1.Lsmdb.GetKVs:output_type -> lsmdb.v1.GetKVsReply
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_lsmdb_v1_lsmdb_proto_init() }
func file_api_lsmdb_v1_lsmdb_proto_init() {
	if File_api_lsmdb_v1_lsmdb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKVsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKVsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferKVRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferKVReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDBWebRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDBWebReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDBRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDBReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutStrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutStrReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseDBRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseDBReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseDBWebRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lsmdb_v1_lsmdb_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseDBWebReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_lsmdb_v1_lsmdb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_lsmdb_v1_lsmdb_proto_goTypes,
		DependencyIndexes: file_api_lsmdb_v1_lsmdb_proto_depIdxs,
		MessageInfos:      file_api_lsmdb_v1_lsmdb_proto_msgTypes,
	}.Build()
	File_api_lsmdb_v1_lsmdb_proto = out.File
	file_api_lsmdb_v1_lsmdb_proto_rawDesc = nil
	file_api_lsmdb_v1_lsmdb_proto_goTypes = nil
	file_api_lsmdb_v1_lsmdb_proto_depIdxs = nil
}
