// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.0
// - protoc             v4.24.2
// source: api/lsmdb/v1/lsmdb.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLsmdbOpenDB = "/lsmdb.v1.Lsmdb/OpenDB"
const OperationLsmdbPutStr = "/lsmdb.v1.Lsmdb/PutStr"

type LsmdbHTTPServer interface {
	// OpenDB Sends a register
	OpenDB(context.Context, *OpenDBRequest) (*OpenDBReply, error)
	PutStr(context.Context, *PutStrRequest) (*PutStrReply, error)
}

func RegisterLsmdbHTTPServer(s *http.Server, srv LsmdbHTTPServer) {
	r := s.Route("/")
	r.POST("/lsmdb/opendb", _Lsmdb_OpenDB0_HTTP_Handler(srv))
	r.POST("/lsmdb/putstr", _Lsmdb_PutStr0_HTTP_Handler(srv))
}

func _Lsmdb_OpenDB0_HTTP_Handler(srv LsmdbHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OpenDBRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLsmdbOpenDB)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OpenDB(ctx, req.(*OpenDBRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OpenDBReply)
		return ctx.Result(200, reply)
	}
}

func _Lsmdb_PutStr0_HTTP_Handler(srv LsmdbHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PutStrRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLsmdbPutStr)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PutStr(ctx, req.(*PutStrRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PutStrReply)
		return ctx.Result(200, reply)
	}
}

type LsmdbHTTPClient interface {
	OpenDB(ctx context.Context, req *OpenDBRequest, opts ...http.CallOption) (rsp *OpenDBReply, err error)
	PutStr(ctx context.Context, req *PutStrRequest, opts ...http.CallOption) (rsp *PutStrReply, err error)
}

type LsmdbHTTPClientImpl struct {
	cc *http.Client
}

func NewLsmdbHTTPClient(client *http.Client) LsmdbHTTPClient {
	return &LsmdbHTTPClientImpl{client}
}

func (c *LsmdbHTTPClientImpl) OpenDB(ctx context.Context, in *OpenDBRequest, opts ...http.CallOption) (*OpenDBReply, error) {
	var out OpenDBReply
	pattern := "/lsmdb/opendb"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLsmdbOpenDB))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *LsmdbHTTPClientImpl) PutStr(ctx context.Context, in *PutStrRequest, opts ...http.CallOption) (*PutStrReply, error) {
	var out PutStrReply
	pattern := "/lsmdb/putstr"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLsmdbPutStr))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
