// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: api/etcd/v1/etcd.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Etcd_Put_FullMethodName = "/etcd.v1.Etcd/Put"
	Etcd_Get_FullMethodName = "/etcd.v1.Etcd/Get"
)

// EtcdClient is the client API for Etcd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EtcdClient interface {
	Put(ctx context.Context, in *EtcdPutRequest, opts ...grpc.CallOption) (*EtcdPutReply, error)
	Get(ctx context.Context, in *EtcdGetRequest, opts ...grpc.CallOption) (*EtcdGetReply, error)
}

type etcdClient struct {
	cc grpc.ClientConnInterface
}

func NewEtcdClient(cc grpc.ClientConnInterface) EtcdClient {
	return &etcdClient{cc}
}

func (c *etcdClient) Put(ctx context.Context, in *EtcdPutRequest, opts ...grpc.CallOption) (*EtcdPutReply, error) {
	out := new(EtcdPutReply)
	err := c.cc.Invoke(ctx, Etcd_Put_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdClient) Get(ctx context.Context, in *EtcdGetRequest, opts ...grpc.CallOption) (*EtcdGetReply, error) {
	out := new(EtcdGetReply)
	err := c.cc.Invoke(ctx, Etcd_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EtcdServer is the server API for Etcd service.
// All implementations must embed UnimplementedEtcdServer
// for forward compatibility
type EtcdServer interface {
	Put(context.Context, *EtcdPutRequest) (*EtcdPutReply, error)
	Get(context.Context, *EtcdGetRequest) (*EtcdGetReply, error)
	mustEmbedUnimplementedEtcdServer()
}

// UnimplementedEtcdServer must be embedded to have forward compatible implementations.
type UnimplementedEtcdServer struct {
}

func (UnimplementedEtcdServer) Put(context.Context, *EtcdPutRequest) (*EtcdPutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedEtcdServer) Get(context.Context, *EtcdGetRequest) (*EtcdGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedEtcdServer) mustEmbedUnimplementedEtcdServer() {}

// UnsafeEtcdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EtcdServer will
// result in compilation errors.
type UnsafeEtcdServer interface {
	mustEmbedUnimplementedEtcdServer()
}

func RegisterEtcdServer(s grpc.ServiceRegistrar, srv EtcdServer) {
	s.RegisterService(&Etcd_ServiceDesc, srv)
}

func _Etcd_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EtcdPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Etcd_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdServer).Put(ctx, req.(*EtcdPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etcd_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EtcdGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Etcd_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdServer).Get(ctx, req.(*EtcdGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Etcd_ServiceDesc is the grpc.ServiceDesc for Etcd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Etcd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "etcd.v1.Etcd",
	HandlerType: (*EtcdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Etcd_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Etcd_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/etcd/v1/etcd.proto",
}
