// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.3
// - protoc             v3.6.1
// source: api/register/v1/register.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRegisterRegister = "/register.v1.Register/Register"

type RegisterHTTPServer interface {
	// Register Sends a register
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
}

func RegisterRegisterHTTPServer(s *http.Server, srv RegisterHTTPServer) {
	r := s.Route("/")
	r.GET("/register", _Register_Register0_HTTP_Handler(srv))
}

func _Register_Register0_HTTP_Handler(srv RegisterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRegisterRegister)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Register(ctx, req.(*RegisterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegisterReply)
		return ctx.Result(200, reply)
	}
}

type RegisterHTTPClient interface {
	Register(ctx context.Context, req *RegisterRequest, opts ...http.CallOption) (rsp *RegisterReply, err error)
}

type RegisterHTTPClientImpl struct {
	cc *http.Client
}

func NewRegisterHTTPClient(client *http.Client) RegisterHTTPClient {
	return &RegisterHTTPClientImpl{client}
}

func (c *RegisterHTTPClientImpl) Register(ctx context.Context, in *RegisterRequest, opts ...http.CallOption) (*RegisterReply, error) {
	var out RegisterReply
	pattern := "/register"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRegisterRegister))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
