server:
  http:
    addr: 0.0.0.0:8004
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8005
    timeout: 1s
data:
  dbtype: rocksdb
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  etcd:
    username: root
    password: password
    cluster_addrs: ["127.0.0.1:2479", "127.0.0.1:2579", "127.0.0.1:2679"]
  leveldb:
    cache_dir: "/home/tsand/go_code/db/"
    data_dir: "/"
    block_size: 32
    compaction_table_size: 32
    iterator_sampling_rate: 4
    write_buffer: 32
  oss:
    endpoint: 127.0.0.1:9000
    access_key: admin
    secret_key: Ecbox2022!
    region: "cn-north-1"
  node_name: node1