// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: huajian/v1/huajian.proto
// Protobuf C++ Version: 5.27.0

#include "huajian/v1/huajian.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace helloworld {
namespace v1 {

inline constexpr GetModelRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : db_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetModelRequest::GetModelRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetModelRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetModelRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetModelRequestDefaultTypeInternal() {}
  union {
    GetModelRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetModelRequestDefaultTypeInternal _GetModelRequest_default_instance_;

inline constexpr GetModelReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetModelReply::GetModelReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetModelReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetModelReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetModelReplyDefaultTypeInternal() {}
  union {
    GetModelReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetModelReplyDefaultTypeInternal _GetModelReply_default_instance_;
}  // namespace v1
}  // namespace helloworld
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_huajian_2fv1_2fhuajian_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_huajian_2fv1_2fhuajian_2eproto = nullptr;
const ::uint32_t
    TableStruct_huajian_2fv1_2fhuajian_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::helloworld::v1::GetModelRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::helloworld::v1::GetModelRequest, _impl_.db_name_),
        PROTOBUF_FIELD_OFFSET(::helloworld::v1::GetModelRequest, _impl_.key_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::helloworld::v1::GetModelReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::helloworld::v1::GetModelReply, _impl_.value_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::helloworld::v1::GetModelRequest)},
        {10, -1, -1, sizeof(::helloworld::v1::GetModelReply)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::helloworld::v1::_GetModelRequest_default_instance_._instance,
    &::helloworld::v1::_GetModelReply_default_instance_._instance,
};
const char descriptor_table_protodef_huajian_2fv1_2fhuajian_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030huajian/v1/huajian.proto\022\rhelloworld.v"
    "1\032\034google/api/annotations.proto\"/\n\017GetMo"
    "delRequest\022\017\n\007db_name\030\001 \001(\t\022\013\n\003key\030\002 \001(\t"
    "\"\036\n\rGetModelReply\022\r\n\005value\030\001 \001(\0142q\n\007Huaj"
    "ian\022f\n\010GetModel\022\036.helloworld.v1.GetModel"
    "Request\032\034.helloworld.v1.GetModelReply\"\034\202"
    "\323\344\223\002\026\022\024/get/{db_name}/{key}B_\n\031dev.krato"
    "s.api.huajian.v1B\016HuajianProtoV1P\001Z0gith"
    "ub.com/ZLSMDB/lsmdb_server/api/huajian/v"
    "1;v1b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_huajian_2fv1_2fhuajian_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fapi_2fannotations_2eproto,
};
static ::absl::once_flag descriptor_table_huajian_2fv1_2fhuajian_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_huajian_2fv1_2fhuajian_2eproto = {
    false,
    false,
    372,
    descriptor_table_protodef_huajian_2fv1_2fhuajian_2eproto,
    "huajian/v1/huajian.proto",
    &descriptor_table_huajian_2fv1_2fhuajian_2eproto_once,
    descriptor_table_huajian_2fv1_2fhuajian_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_huajian_2fv1_2fhuajian_2eproto::offsets,
    file_level_enum_descriptors_huajian_2fv1_2fhuajian_2eproto,
    file_level_service_descriptors_huajian_2fv1_2fhuajian_2eproto,
};
namespace helloworld {
namespace v1 {
// ===================================================================

class GetModelRequest::_Internal {
 public:
};

GetModelRequest::GetModelRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:helloworld.v1.GetModelRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetModelRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::helloworld::v1::GetModelRequest& from_msg)
      : db_name_(arena, from.db_name_),
        key_(arena, from.key_),
        _cached_size_{0} {}

GetModelRequest::GetModelRequest(
    ::google::protobuf::Arena* arena,
    const GetModelRequest& from)
    : ::google::protobuf::Message(arena) {
  GetModelRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:helloworld.v1.GetModelRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetModelRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : db_name_(arena),
        key_(arena),
        _cached_size_{0} {}

inline void GetModelRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetModelRequest::~GetModelRequest() {
  // @@protoc_insertion_point(destructor:helloworld.v1.GetModelRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetModelRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.db_name_.Destroy();
  _impl_.key_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
GetModelRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(GetModelRequest, _impl_._cached_size_),
              false,
          },
          &GetModelRequest::MergeImpl,
          &GetModelRequest::kDescriptorMethods,
          &descriptor_table_huajian_2fv1_2fhuajian_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 48, 2> GetModelRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GetModelRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::helloworld::v1::GetModelRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string key = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GetModelRequest, _impl_.key_)}},
    // string db_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetModelRequest, _impl_.db_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string db_name = 1;
    {PROTOBUF_FIELD_OFFSET(GetModelRequest, _impl_.db_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string key = 2;
    {PROTOBUF_FIELD_OFFSET(GetModelRequest, _impl_.key_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\35\7\3\0\0\0\0\0"
    "helloworld.v1.GetModelRequest"
    "db_name"
    "key"
  }},
};

PROTOBUF_NOINLINE void GetModelRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:helloworld.v1.GetModelRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.db_name_.ClearToEmpty();
  _impl_.key_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* GetModelRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:helloworld.v1.GetModelRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string db_name = 1;
  if (!this->_internal_db_name().empty()) {
    const std::string& _s = this->_internal_db_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "helloworld.v1.GetModelRequest.db_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string key = 2;
  if (!this->_internal_key().empty()) {
    const std::string& _s = this->_internal_key();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "helloworld.v1.GetModelRequest.key");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:helloworld.v1.GetModelRequest)
  return target;
}

::size_t GetModelRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:helloworld.v1.GetModelRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string db_name = 1;
  if (!this->_internal_db_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_db_name());
  }

  // string key = 2;
  if (!this->_internal_key().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_key());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void GetModelRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetModelRequest*>(&to_msg);
  auto& from = static_cast<const GetModelRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:helloworld.v1.GetModelRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_db_name().empty()) {
    _this->_internal_set_db_name(from._internal_db_name());
  }
  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetModelRequest::CopyFrom(const GetModelRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:helloworld.v1.GetModelRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetModelRequest::InternalSwap(GetModelRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.db_name_, &other->_impl_.db_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
}

::google::protobuf::Metadata GetModelRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetModelReply::_Internal {
 public:
};

GetModelReply::GetModelReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:helloworld.v1.GetModelReply)
}
inline PROTOBUF_NDEBUG_INLINE GetModelReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::helloworld::v1::GetModelReply& from_msg)
      : value_(arena, from.value_),
        _cached_size_{0} {}

GetModelReply::GetModelReply(
    ::google::protobuf::Arena* arena,
    const GetModelReply& from)
    : ::google::protobuf::Message(arena) {
  GetModelReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:helloworld.v1.GetModelReply)
}
inline PROTOBUF_NDEBUG_INLINE GetModelReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_(arena),
        _cached_size_{0} {}

inline void GetModelReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetModelReply::~GetModelReply() {
  // @@protoc_insertion_point(destructor:helloworld.v1.GetModelReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetModelReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.value_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
GetModelReply::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(GetModelReply, _impl_._cached_size_),
              false,
          },
          &GetModelReply::MergeImpl,
          &GetModelReply::kDescriptorMethods,
          &descriptor_table_huajian_2fv1_2fhuajian_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GetModelReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GetModelReply_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::helloworld::v1::GetModelReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes value = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetModelReply, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes value = 1;
    {PROTOBUF_FIELD_OFFSET(GetModelReply, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetModelReply::Clear() {
// @@protoc_insertion_point(message_clear_start:helloworld.v1.GetModelReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* GetModelReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:helloworld.v1.GetModelReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes value = 1;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:helloworld.v1.GetModelReply)
  return target;
}

::size_t GetModelReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:helloworld.v1.GetModelReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes value = 1;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void GetModelReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetModelReply*>(&to_msg);
  auto& from = static_cast<const GetModelReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:helloworld.v1.GetModelReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetModelReply::CopyFrom(const GetModelReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:helloworld.v1.GetModelReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetModelReply::InternalSwap(GetModelReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
}

::google::protobuf::Metadata GetModelReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace helloworld
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_huajian_2fv1_2fhuajian_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
