// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: huajian/v1/huajian.proto

#include "huajian/v1/huajian.pb.h"
#include "huajian/v1/huajian.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace helloworld {
namespace v1 {

static const char* Huajian_method_names[] = {
  "/helloworld.v1.Huajian/GetModel",
};

std::unique_ptr< Huajian::Stub> Huajian::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Huajian::Stub> stub(new Huajian::Stub(channel, options));
  return stub;
}

Huajian::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetModel_(Huajian_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Huajian::Stub::GetModel(::grpc::ClientContext* context, const ::helloworld::v1::GetModelRequest& request, ::helloworld::v1::GetModelReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::helloworld::v1::GetModelRequest, ::helloworld::v1::GetModelReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetModel_, context, request, response);
}

void Huajian::Stub::async::GetModel(::grpc::ClientContext* context, const ::helloworld::v1::GetModelRequest* request, ::helloworld::v1::GetModelReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::helloworld::v1::GetModelRequest, ::helloworld::v1::GetModelReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetModel_, context, request, response, std::move(f));
}

void Huajian::Stub::async::GetModel(::grpc::ClientContext* context, const ::helloworld::v1::GetModelRequest* request, ::helloworld::v1::GetModelReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetModel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::helloworld::v1::GetModelReply>* Huajian::Stub::PrepareAsyncGetModelRaw(::grpc::ClientContext* context, const ::helloworld::v1::GetModelRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::helloworld::v1::GetModelReply, ::helloworld::v1::GetModelRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetModel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::helloworld::v1::GetModelReply>* Huajian::Stub::AsyncGetModelRaw(::grpc::ClientContext* context, const ::helloworld::v1::GetModelRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetModelRaw(context, request, cq);
  result->StartCall();
  return result;
}

Huajian::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Huajian_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Huajian::Service, ::helloworld::v1::GetModelRequest, ::helloworld::v1::GetModelReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Huajian::Service* service,
             ::grpc::ServerContext* ctx,
             const ::helloworld::v1::GetModelRequest* req,
             ::helloworld::v1::GetModelReply* resp) {
               return service->GetModel(ctx, req, resp);
             }, this)));
}

Huajian::Service::~Service() {
}

::grpc::Status Huajian::Service::GetModel(::grpc::ServerContext* context, const ::helloworld::v1::GetModelRequest* request, ::helloworld::v1::GetModelReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace helloworld
}  // namespace v1

